apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: classifier
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  selector:
    matchLabels:
      {{- toYaml .Values.selector | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.scrapeInterval }}
